# Generated by Django 4.0.1 on 2022-02-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_listing_comment_listing_alter_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=None),
        ),
    ]
